### PR TITLE
Fix/lobbies

### LINKED ISSUE #88: feature: get lobby by userID and guildID
See title

### PR DESCRIPTION
**Pull request by sam1357**
- Implemented routes `GET` `lobbies/{guild_id}/{user_Id}` and `GET` `/lobbies`
- Implemented tests and functions for above routes
- `PUT` `lobbies/{guild_Id}/{leader_id}/users` has been updated to `DELETE` `lobbies/{guild_id}/{leader_id}/{user_id}` (only deleting one user at a time due to database library limitation
- Updated API spec to reflect new changes 
- Added middleware handling and improved log readability + log file output

Closes #88

### CODE REVIEW

File: src/lobbies/index.ts [hunk 1]
```diff
@@ -165,25 +162,57 @@ export async function addLobbyUsers(guildID: bigint | number, leaderID: bigint |
...
  * @param {bigint | number} leaderID - the user ID of the user who owns the lobby
- * @param {string[]} data - an array of user IDs to delete from the lobby
+ * @param {bigint | number} userID - a userID to delete from the lobby
  * @throws {createErrors<400>} - if the input array is empty
  * @throws {createErrors<404>} - if the lobby cannot be found
  * @returns {Promise<Record<string, never>>}
  */
-export async function deleteLobbyUsers(guildID: bigint | number, leaderID: bigint | number, data: string[]): Promise<Record<string, never>> {
-  if (data.length === 0) {
+export async function deleteLobbyUsers(guildID: bigint | number, leaderID: bigint | number, userID: bigint | number): Promise<Record<string, never>> {
```
Comment (MasterOfCubesAU) [inline src/lobbies/index.ts:174]: Rename function to `deleteLobbyUser`

**Review by MasterOfCubesAU — CHANGES_REQUESTED** [review]

File: src/server.ts [hunk 2]
```diff
@@ -47,6 +48,17 @@ app.use(
 
 app.use('/v1', v1Route);
 
+app.use((err: any, req: Request, res: Response, next: NextFunction) => {
+  const statusCode = err.status || err.statusCode || 500;
+  console.log(statusCode === 500 ? chalk.hex('#FF0000').bold(err) : chalk.hex('#FFA500').bold(err.message));
```
Comment (MasterOfCubesAU) [inline src/server.ts:53]:
```suggestion
```

**Review by MasterOfCubesAU — CHANGES_REQUESTED** [review]

**Review by MasterOfCubesAU — APPROVED** [review]
